version: '3.8'
services:

  nginx:
    image: nginx
    ports:
      - "23333:80"
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/include:/etc/nginx/include
      - ./tmp/log:/var/log/nginx
      - ./tmp/cache:/opt/nginx

