version: '3.7'

services:
  cis:
    image: quay.io/martinhelmich/prometheus-nginxlog-exporter:v1
    networks:
      flix-network:
        aliases:
          - "cis-nginxlog-exporter"
    volumes:
      - log:/var/log/nginx:ro
    command:
      - "--config-file=/etc/nginxlog-exporter/config.hcl"
    ports:
      - "54100:4040"
    volumes:
      - ./nginxlog-exporter/nginxlog-exporter.hcl:/etc/nginxlog-exporter/config.hcl
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.cis == yes
      restart_policy:
        condition: on-failure
networks:
  flix-network:
      external: true
volumes:
  log:
    external: true
