version: '3.7'

services:
  nginx:
    image: adam21b/proxy:latest
    networks:
      flix-network:
        aliases:
          - "proxy-nginx"
    volumes:
      - log:/var/log/nginx
      - cache:/opt/nginx
    ports:
      - target: 80
        published: 80
        mode: host
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.proxy == yes
      restart_policy:
        condition: on-failure

  cis-edge:
    image: adam21b/cis-edge:latest
    networks:
      flix-network:
        aliases:
          - "cis-edge"
    volumes:
      - log:/var/log/nginx
      - cache:/opt/nginx
    ports:
      - target: 80
        published: 80
        mode: host
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.cis == yes
      restart_policy:
        condition: on-failure

  india-edge:
    image: adam21b/india-edge:latest
    networks:
      flix-network:
        aliases:
          - "india-edge"
    volumes:
      - log:/var/log/nginx
      - cache:/opt/nginx
    ports:
      - target: 80
        published: 80
        mode: host
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.india == yes
      restart_policy:
        condition: on-failure

  sport-edge:
    image: adam21b/sport-edge:latest
    networks:
      flix-network:
        aliases:
          - "sport-edge"
    volumes:
      - log:/var/log/nginx
      - cache:/opt/nginx
    ports:
      - target: 80
        published: 80
        mode: host
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.sport == yes
      restart_policy:
        condition: on-failure
networks:
  flix-network:
      external: true

volumes:
  log:
  cache: