version: '3.7'

services:
  nginx:
    image: adam21b/proxy:latest
    networks:
      flix-network:
        aliases:
          - "proxy-nginx"
    volumes:
      - log:/var/log/nginx
      - cache:/opt/nginx
    ports:
      - target: 80
        published: 80
        mode: host
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.proxy == yes
      restart_policy:
        condition: on-failure

networks:
  flix-network:
      external: true

volumes:
  log:
  cache: