version: '3.7'

services:
  nginx:
    image: nginx
    networks:
      flix-network:
        aliases:
          - "proxy-nginx"
    volumes:
      - ./sites-enabled:/etc/nginx/sites-enabled
      - /var/log/nginx:/var/log/nginx
      - /opt/nginx:/opt/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - target: 80
        published: 23333
        mode: host
    deploy:
      placement:
        constraints:
          - node.labels.proxy == yes
      restart_policy:
        condition: on-failure

networks:
  flix-network:
      external: true